controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authentication_token:
    path: /authentication_token
    methods: ['POST']

api_refresh_token:
    path: /authentication_token/refresh
    controller: App\Controller\RefreshTokenController::refreshAction
    methods: POST

app_logout:
    path: /logout
