api_platform:
    formats:
      jsonld: [ 'application/ld+json' ]
      html: [ 'text/html' ]
      json: [ 'application/json' ]
      jsonhal: [ 'application/hal+json' ]
    swagger:
      api_keys:
          JWT:
              name: Authorization
              type: header
































#    enable_docs: false
#    enable_entrypoint: false
#    enable_swagger: false
#    enable_swagger_ui: false
#'%env(bool:ENABLE_API_DOCS)%'
