nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['http://localhost:3000']  # Replace this with your front-end domain
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/': null
